#!/bin/bash

# A simple script to output the list of affected apps

if OUTPUT=$(npx nx affected:apps --base=${AFFECTED_BASE} --plain 2> /dev/null); then
  AFFECTED_APPS=$(echo $OUTPUT | tail -1)
else
  # TODO: replace with list of all apps
  echo "Could not find ref ${AFFECTED_BASE}, using all apps"
  AFFECTED_APPS="api web reg-scraper"
fi

NX_AFFECTED_APPS=$(echo $AFFECTED_APPS | tr " " ",")
echo "AFFECTED_APPS=$AFFECTED_APPS" >> $GITHUB_ENV
echo "NX_AFFECTED_APPS=$NX_AFFECTED_APPS" >> $GITHUB_ENV
echo "Affected apps: $AFFECTED_APPS"
