import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@admin-web/styles/Home.module.css'
import { ApolloProvider } from '@apollo/client'
import { client } from '@admin-web/services/apollo'
import Test from './api/Test'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <ApolloProvider client={client}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <Test />
        </main>
      </ApolloProvider>
    </>
  )
}
