FROM node:16.17.0-buster AS cugetreg-base
WORKDIR /app

ARG TARGETARCH

RUN if test "$TARGETARCH" = "arm64"; then apt-get update; fi
RUN if test "$TARGETARCH" = "arm64"; then apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev; fi

RUN npm install -g pnpm

COPY .npmrc package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile
