services:
  postgres:
    image: postgres:16-alpine
    container_name: cugetreg-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: cugetreg
      POSTGRES_PASSWORD: cugetreg
      POSTGRES_DB: cugetreg
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  mongo:
    image: mongo:5.0.10
    container_name: cugetreg-mongo
    restart: unless-stopped
    volumes:
      - ./volumes/mongo:/data/db
    ports:
      - 27017:27017

  redis:
    image: redis:latest
    container_name: cugetreg-redis
    volumes:
      - ./volumes/redis:/data
    ports:
      - 6379:6379
