import { Course, DayOfWeek, GenEdType, StudyProgram } from '@cgr/codegen'

export const mockCourseData: Course[] = [
  {
    studyProgram: StudyProgram.S,
    semester: '2',
    academicYear: '2564',
    courseNo: '0201122',
    abbrName: 'MGT PUB DISASTER',
    courseNameTh: 'การจัดการสาธารณภัย',
    courseNameEn: 'MANAGEMENT OF PUBLIC DISASTER',
    faculty: '02',
    department: 'ศูนย์การศึกษาทั่วไป',
    credit: 3,
    creditHours: 'LECT 3.0 CR(LECT 3.0 HR)',
    courseCondition: '-',
    courseDescTh: null,
    courseDescEn: null,
    genEdType: GenEdType.In,
    midterm: null,
    final: null,
    sections: [
      {
        genEdType: GenEdType.In,
        sectionNo: '1',
        closed: false,
        capacity: {
          current: 0,
          max: 80,
        },
        note: 'GENED-IN',
        classes: [
          {
            type: 'LECT',
            dayOfWeek: DayOfWeek.Tu,
            period: {
              start: '13:00',
              end: '16:00',
            },
            room: '309',
            building: 'CUP13',
            teachers: ['STAFF'],
          },
        ],
      },
    ],
  },
  {
    studyProgram: StudyProgram.S,
    semester: '2',
    academicYear: '2564',
    courseNo: '0201107',
    abbrName: 'LRN STUD ACT',
    courseNameTh: 'การเรียนรู้ผ่านกิจกรรมนิสิต',
    courseNameEn: 'LEARNING THROUGH STUDENT ACTIVITIES',
    faculty: '02',
    department: 'ศูนย์การศึกษาทั่วไป',
    credit: 3,
    creditHours: 'LECT 1.0 CR + NL36 2.0 CR(LECT 1.0 HR + FWK 6.0 HR)',
    courseCondition: '-',
    courseDescTh: null,
    courseDescEn: null,
    genEdType: GenEdType.In,
    midterm: null,
    final: null,
    sections: [
      {
        genEdType: GenEdType.In,
        sectionNo: '1',
        closed: false,
        capacity: {
          current: 0,
          max: 30,
        },
        note: 'GENED-IN',
        classes: [
          {
            type: 'LECT',
            dayOfWeek: DayOfWeek.We,
            period: {
              start: '13:00',
              end: '14:00',
            },
            room: '202',
            building: 'MAHIT',
            teachers: ['STAFF'],
          },
          {
            type: 'FWK',
            dayOfWeek: DayOfWeek.We,
            period: {
              start: '14:00',
              end: '16:00',
            },
            room: '202',
            building: 'MAHIT',
            teachers: ['STAFF'],
          },
          {
            type: 'FWK',
            dayOfWeek: DayOfWeek.Ia,
            period: {
              start: DayOfWeek.Ia,
              end: DayOfWeek.Ia,
            },
            room: null,
            building: null,
            teachers: ['STAFF'],
          },
        ],
      },
      {
        genEdType: GenEdType.In,
        sectionNo: '2',
        closed: false,
        capacity: {
          current: 0,
          max: 30,
        },
        note: 'GENED-IN',
        classes: [
          {
            type: 'LECT',
            dayOfWeek: DayOfWeek.We,
            period: {
              start: '13:00',
              end: '14:00',
            },
            room: '202',
            building: 'MAHIT',
            teachers: ['STAFF'],
          },
          {
            type: 'FWK',
            dayOfWeek: DayOfWeek.We,
            period: {
              start: '14:00',
              end: '16:00',
            },
            room: '202',
            building: 'MAHIT',
            teachers: ['STAFF'],
          },
          {
            type: 'FWK',
            dayOfWeek: DayOfWeek.Ia,
            period: {
              start: DayOfWeek.Ia,
              end: DayOfWeek.Ia,
            },
            room: null,
            building: null,
            teachers: ['STAFF'],
          },
        ],
      },
    ],
  },
  {
    studyProgram: StudyProgram.S,
    semester: '2',
    academicYear: '2564',
    courseNo: '0123104',
    abbrName: 'UNIV THAI READING',
    courseNameTh: 'การอ่านภาษาไทยระดับอุดมศึกษา',
    courseNameEn: 'UNIVERSITY LEVEL OF THAI READING',
    faculty: '01',
    department: 'สถาบันภาษาไทยสิรินธร',
    credit: 3,
    creditHours: 'LECT 1.0 CR + NL23 2.0 CR(LECT 1.0 HR + PRAC 4.0 HR)',
    courseCondition: '-',
    courseDescTh: null,
    courseDescEn: null,
    genEdType: GenEdType.Hu,
    midterm: {
      date: '2565-03-09T00:00:00.000Z',
      period: {
        start: '16:00',
        end: '19:00',
      },
    },
    final: {
      date: '2565-05-11T00:00:00.000Z',
      period: {
        start: '16:00',
        end: '19:00',
      },
    },
    sections: [
      {
        genEdType: GenEdType.Hu,
        sectionNo: '1',
        closed: false,
        capacity: {
          current: 0,
          max: 60,
        },
        note: 'GENED-HU (E-LEARNING)',
        classes: [
          {
            type: 'LECT',
            dayOfWeek: DayOfWeek.We,
            period: {
              start: '16:00',
              end: '17:00',
            },
            room: '201',
            building: 'MAHIT',
            teachers: ['WSN'],
          },
          {
            type: 'PRAC',
            dayOfWeek: DayOfWeek.We,
            period: {
              start: '17:00',
              end: '19:00',
            },
            room: '201',
            building: 'MAHIT',
            teachers: ['WSN'],
          },
          {
            type: 'PRAC',
            dayOfWeek: DayOfWeek.Ia,
            period: {
              start: DayOfWeek.Ia,
              end: DayOfWeek.Ia,
            },
            room: null,
            building: null,
            teachers: ['WSN'],
          },
        ],
      },
      {
        genEdType: GenEdType.Hu,
        sectionNo: '2',
        closed: false,
        capacity: {
          current: 0,
          max: 60,
        },
        note: 'GENED-HU (E-LEARNING)',
        classes: [
          {
            type: 'LECT',
            dayOfWeek: DayOfWeek.We,
            period: {
              start: '16:00',
              end: '17:00',
            },
            room: '202',
            building: 'MAHIT',
            teachers: ['NSP'],
          },
          {
            type: 'PRAC',
            dayOfWeek: DayOfWeek.We,
            period: {
              start: '17:00',
              end: '19:00',
            },
            room: '202',
            building: 'MAHIT',
            teachers: ['NSP'],
          },
          {
            type: 'PRAC',
            dayOfWeek: DayOfWeek.Ia,
            period: {
              start: DayOfWeek.Ia,
              end: DayOfWeek.Ia,
            },
            room: null,
            building: null,
            teachers: ['NSP'],
          },
        ],
      },
      {
        genEdType: GenEdType.Hu,
        sectionNo: '3',
        closed: false,
        capacity: {
          current: 0,
          max: 60,
        },
        note: 'GENED-HU (E-LEARNING)',
        classes: [
          {
            type: 'LECT',
            dayOfWeek: DayOfWeek.We,
            period: {
              start: '16:00',
              end: '17:00',
            },
            room: '401',
            building: 'MAHIT',
            teachers: ['NPR'],
          },
          {
            type: 'PRAC',
            dayOfWeek: DayOfWeek.We,
            period: {
              start: '17:00',
              end: '19:00',
            },
            room: '401',
            building: 'MAHIT',
            teachers: ['NPR'],
          },
          {
            type: 'PRAC',
            dayOfWeek: DayOfWeek.Ia,
            period: {
              start: DayOfWeek.Ia,
              end: DayOfWeek.Ia,
            },
            room: null,
            building: null,
            teachers: ['NPR'],
          },
        ],
      },
      {
        genEdType: GenEdType.Hu,
        sectionNo: '4',
        closed: false,
        capacity: {
          current: 0,
          max: 60,
        },
        note: 'GENED-HU (E-LEARNING)',
        classes: [
          {
            type: 'LECT',
            dayOfWeek: DayOfWeek.We,
            period: {
              start: '16:00',
              end: '17:00',
            },
            room: '402',
            building: 'MAHIT',
            teachers: ['SCW'],
          },
          {
            type: 'PRAC',
            dayOfWeek: DayOfWeek.We,
            period: {
              start: '17:00',
              end: '19:00',
            },
            room: '402',
            building: 'MAHIT',
            teachers: ['SCW'],
          },
          {
            type: 'PRAC',
            dayOfWeek: DayOfWeek.Ia,
            period: {
              start: DayOfWeek.Ia,
              end: DayOfWeek.Ia,
            },
            room: null,
            building: null,
            teachers: ['SCW'],
          },
        ],
      },
      {
        genEdType: GenEdType.Hu,
        sectionNo: '5',
        closed: false,
        capacity: {
          current: 0,
          max: 60,
        },
        note: 'GENED-HU (E-LEARNING)',
        classes: [
          {
            type: 'LECT',
            dayOfWeek: DayOfWeek.We,
            period: {
              start: '16:00',
              end: '17:00',
            },
            room: '412',
            building: 'MAHIT',
            teachers: ['SSN'],
          },
          {
            type: 'PRAC',
            dayOfWeek: DayOfWeek.We,
            period: {
              start: '17:00',
              end: '19:00',
            },
            room: '412',
            building: 'MAHIT',
            teachers: ['SSN'],
          },
          {
            type: 'PRAC',
            dayOfWeek: DayOfWeek.Ia,
            period: {
              start: DayOfWeek.Ia,
              end: DayOfWeek.Ia,
            },
            room: null,
            building: null,
            teachers: ['SSN'],
          },
        ],
      },
      {
        genEdType: GenEdType.Hu,
        sectionNo: '6',
        closed: true,
        capacity: {
          current: 0,
          max: 60,
        },
        note: 'GENED-HU (E-LEARNING)',
        classes: [
          {
            type: 'LECT',
            dayOfWeek: DayOfWeek.We,
            period: {
              start: '16:00',
              end: '17:00',
            },
            room: '412',
            building: 'MAHIT',
            teachers: ['WSN'],
          },
          {
            type: 'PRAC',
            dayOfWeek: DayOfWeek.We,
            period: {
              start: '17:00',
              end: '19:00',
            },
            room: '412',
            building: 'MAHIT',
            teachers: ['WSN'],
          },
          {
            type: 'PRAC',
            dayOfWeek: DayOfWeek.Ia,
            period: {
              start: DayOfWeek.Ia,
              end: DayOfWeek.Ia,
            },
            room: null,
            building: null,
            teachers: ['WSN'],
          },
        ],
      },
    ],
  },
]
