name: Backlog
description: Create a new task
title: '[BACKLOG] '
body:
  - type: markdown
    attributes:
      value: |
        ### If this task is part of an **Epic**, do not forget to add label in the format `Epic: <epic name>`. Ex: `Epic: Scraper Optimization`
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What's the reason behind this task?
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: What do you want the assignees to do?
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: What should the assignees know, if they take this task?
    validations:
      required: false
  - type: checkboxes
    id: teams
    attributes:
      label: Related Teams
      description: What teams are related to this task?
      options:
        - label: Frontend
        - label: Backend
        - label: Data
        - label: Design
        - label: Infra
        - label: QA
  - type: textarea
    id: advisors
    attributes:
      label: Task Advisors
      description: Who are the task advisors?
    validations:
      required: false
