services:
  db:
    image: postgres:18
    restart: always
    container_name: cugetreg-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./volumes/postgres:/var/lib/postgresql

    ports:
      - "${DB_PORT}:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  redis:
    image: redis:latest
    container_name: cugetreg-redis
    volumes:
      - ./volumes/redis:/data
    ports:
      - 6379:6379

networks:
  default:
    name: cugetreg-shared
