name: Add issue and pull request to Project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - ready_to_review

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/thinc-org/projects/3
          github-token: ${{ github.token }}
