name: Build and Publish Docker image

on:
  workflow_call:
    inputs:
      packages:
        description: Packages to build and publish
        required: true
        type: string
      container-registry:
        description: Container registry to push the image to
        default: ghcr.io
        type: string
      image-prefix:
        description: Image prefix of the built image
        type: string
      username:
        description: Username for logging in to the container registry
        type: string
        default: ${{ github.actor }}
      password:
        description: Password for logging in to the container registry
        type: string
        default: ${{ github.token }}
      target-repository:
        description: Target repository for updating deployment declaration
        type: string
        default: ${{ github.repository }}
      target-ref:
        description: Target ref for updating deployment declaration
        type: string
        default: main
      target-directory:
        description: Target directory for updating deployment declaration
        type: string
        default: .
      push:
        description: Enable pushing the image to the container registry
        type: boolean
        default: false

jobs:
  build-and-publish-docker-image:
    name: Build and Publish Docker image

    runs-on: ubuntu-latest

    strategy:
      matrix:
        packages: ${{ fromJson(inputs.packages) }}

    outputs:
      DOCKERFILE_EXISTS: ${{ steps.check-dockerfile.outputs.DOCKERFILE_EXISTS }}

    steps:
      - name: Checkout with tags
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ matrix.packages.ref }}

      - name: Check if Dockerfile exists
        id: check-dockerfile
        run: |
          if [ ! -f apps/${{ matrix.packages.name }}/Dockerfile ]; then
            echo "Dockerfile does not exist"
            echo "DOCKERFILE_EXISTS=false" >> $GITHUB_OUTPUT
          else
            echo "Dockerfile exists"
            echo "DOCKERFILE_EXISTS=true" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        if: steps.check-dockerfile.outputs.DOCKERFILE_EXISTS == 'true'
        uses: docker/setup-buildx-action@v2

      - name: Login to Container Registry
        if: steps.check-dockerfile.outputs.DOCKERFILE_EXISTS == 'true'
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.container-registry }}
          username: ${{ inputs.username || github.actor }}
          password: ${{ inputs.password || github.token }}

      - name: Set frontend env
        if: ${{ matrix.packages.name == 'web' || matrix.packages.name == 'admin-web' }}
        env:
          APP_NAME: ${{ matrix.packages.name }}
          BRANCH: ${{ github.ref_name }}
        run: |
          if [[ $BRANCH == 'main' ]]; then
            echo "$APP_NAME env is set to production"
            mv apps/$APP_NAME/.env.prod apps/$APP_NAME/.env
          elif [[ $BRANCH == 'beta' ]]; then
            echo "$APP_NAME env is set to dev"
            mv apps/$APP_NAME/.env.beta apps/$APP_NAME/.env
          elif [[ $BRANCH == 'dev' ]]; then
            echo "$APP_NAME env is set to beta"
            mv apps/$APP_NAME/.env.dev apps/$APP_NAME/.env
          fi

      - name: Build and push Docker image
        if: steps.check-dockerfile.outputs.DOCKERFILE_EXISTS == 'true'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: apps/${{ matrix.packages.name }}/Dockerfile
          tags: |
            ${{ inputs.container-registry }}/${{ inputs.image-prefix }}/${{ matrix.packages.name }}:${{ matrix.packages.imageTag }}
          push: ${{ inputs.push }}
