name: Continuous Integration
on:
  push:
    # branches:
    #   - main
    #   - beta
  pull_request:

jobs:
  install-deps:
    strategy:
      matrix:
        node-version: [16.17.0]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    uses: ./.github/workflows/reuseable-ci.yaml

  lint:
    strategy:
      matrix:
        node-version: [16.17.0]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    uses: ./.github/workflows/reuseable-ci.yaml
    with:
      target: lint

  test:
    strategy:
      matrix:
        node-version: [16.17.0]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    uses: ./.github/workflows/reuseable-ci.yaml
    with:
      target: test

  build:
    strategy:
      matrix:
        node-version: [16.17.0]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    uses: ./.github/workflows/reuseable-ci.yaml
    with:
      target: build
