name: Continuous Integration
on:
  push:
    # branches:
    #   - main
    #   - beta
  pull_request:

jobs:
  install-deps:
    strategy:
      matrix:
        node-version: [16.17.0]
        platform: [ubuntu-latest]
    uses: ./.github/workflows/reuseable-ci.yaml

  lint:
    strategy:
      matrix:
        node-version: [16.17.0]
        platform: [ubuntu-latest]
    needs: install-deps
    uses: ./.github/workflows/reuseable-ci.yaml
    with:
      target: lint
      runs-on: ${{ matrix.platform }}

  test:
    strategy:
      matrix:
        node-version: [16.17.0]
        platform: [ubuntu-latest]
    needs: install-deps
    uses: ./.github/workflows/reuseable-ci.yaml
    with:
      target: test
      runs-on: ${{ matrix.platform }}

  build:
    strategy:
      matrix:
        node-version: [16.17.0]
        platform: [ubuntu-latest]
    needs: install-deps
    uses: ./.github/workflows/reuseable-ci.yaml
    with:
      target: build
      runs-on: ${{ matrix.platform }}
