name: Deploy to Production

on:
  push:
    branches: [master]

jobs:
  deploy:
    strategy:
      matrix:
        node-version: [14.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Use gcloud CLI
        run: gcloud auth configure-docker && gcloud info

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Build Image
        run: docker build --tag gcr.io/{{ secrets.GCP_PROJECT_ID }}/cugetreg-frontend -t cugetreg-frontend .

      - name: Push Image to Google Container Registry
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/cugetreg-frontend:latest

      - name: Pull the updated image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            docker pull gcr.io/{{ secrets.GCP_PROJECT_ID }}/cugetreg-frontend:latest &&
            cd /home/sharedFolder/ &&
            docker-compose up -d &&
            docker rmi $(docker images --filter "dangling=true" -q)
