name: Deploy to Production

on:
  push:
    branches: [master]

permissions:
  contents: read
  pull-requests: write
  repository-projects: read

jobs:
  deploy:
    strategy:
      matrix:
        node-version: [14.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker login using Github Token
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ github.token }}

      - name: Build and push to GitHub Packages
        uses: docker/build-push-action@v2
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          push: true
          tags: ghcr.io/thinc-org/cugetreg/cugetreg-frontend:latest
          cache-from: type=registry,ref=ghcr.io/thinc-org/cugetreg/cugetreg-frontend:buildcache
          cache-to: type=registry,ref=ghcr.io/thinc-org/cugetreg/cugetreg-frontend:buildcache,mode=max
          context: .

      - name: Connect SSLVPN
        uses: thinc-org/openfortivpn-action@master
        with:
          host: ${{ secrets.SSLVPN_HOST }}
          username: ${{ secrets.SSLVPN_USERNAME }}
          password: ${{ secrets.SSLVPN_PASSWORD }}
          trustedCert: ${{ secrets.SSLVPN_TRUSTED_CERT }}

      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            docker pull ghcr.io/thinc-org/cugetreg/cugetreg-frontend:latest
            docker-compose up -d 
            if [[ "$(docker images --filter "dangling=true" -q)" == "" ]]; 
              then echo "No image with <none> tag";
              else docker rmi $(docker images --filter "dangling=true" -q);
            fi
