name: Build and Publish Docker image

on:
  workflow_call:
    inputs:
      packages:
        description: Packages to build and publish
        required: true
        type: string
      environment:
        description: Environment to build and publish e.g. prod, beta, dev
        required: true
        type: string
      container-registry:
        description: Container registry to push the image to
        default: ghcr.io
        type: string
      image-prefix:
        description: Image prefix of the built image
        type: string
      gitops-repository:
        description: Target repository for updating deployment declaration
        type: string
        default: ${{ github.repository }}
      gitops-ref:
        description: Target ref for updating deployment declaration
        type: string
        default: master
      update-mode:
        description: Mode of updating deployment declaration, pr or commit
        type: string
        default: pr
      push:
        description: Enable pushing the image to the container registry
        type: boolean
        default: true
      update:
        description: Enable updating deployment declaration in the target repository
        type: boolean
        default: true
    secrets:
      GH_TOKEN:
        description: GitHub token used to checkout target repository and open PR
        required: true

jobs:
  build-and-publish-docker-image:
    name: Build and Publish Docker image

    runs-on: ubuntu-latest

    strategy:
      matrix:
        packages: ${{ fromJson(inputs.packages) }}

    outputs:
      DOCKERFILE_EXISTS: ${{ steps.check-dockerfile.outputs.DOCKERFILE_EXISTS }}

    steps:
      - name: Checkout with tags
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ matrix.packages.ref }}

      - name: Check if Dockerfile exists
        id: check-dockerfile
        run: |
          if [ ! -f apps/${{ matrix.packages.name }}/Dockerfile ]; then
            echo "Dockerfile does not exist"
            echo "DOCKERFILE_EXISTS=false" >> $GITHUB_OUTPUT
          else
            echo "Dockerfile exists"
            echo "DOCKERFILE_EXISTS=true" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        if: steps.check-dockerfile.outputs.DOCKERFILE_EXISTS == 'true'
        uses: docker/setup-buildx-action@v2

      - name: Login to Container Registry
        if: steps.check-dockerfile.outputs.DOCKERFILE_EXISTS == 'true'
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.container-registry }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set frontend env
        if: ${{ contains(fromJson('["web", "admin-web"]'), matrix.packages.name) && steps.check-dockerfile.outputs.DOCKERFILE_EXISTS == 'true' }}
        env:
          APP_NAME: ${{ matrix.packages.name }}
          BRANCH: ${{ github.ref_name }}
        run: |
          if [[ $BRANCH == 'main' && -f "apps/$APP_NAME/.env.prod" ]]; then
            mv apps/$APP_NAME/.env.prod apps/$APP_NAME/.env
            echo "$APP_NAME env is set to production"
          elif [[ $BRANCH == 'beta' && -f "apps/$APP_NAME/.env.beta" ]]; then
            mv apps/$APP_NAME/.env.beta apps/$APP_NAME/.env
            echo "$APP_NAME env is set to beta"
          elif [[ $BRANCH == 'dev' && -f "apps/$APP_NAME/.env.dev" ]]; then
            mv apps/$APP_NAME/.env.dev apps/$APP_NAME/.env
            echo "$APP_NAME env is set to dev"
          else
            echo "$APP_NAME env is not set. This could be because branch '$BRANCH' is not in [main, beta, dev] or .env file for the branch is not found"
          fi

      - name: Build and push Docker image
        if: steps.check-dockerfile.outputs.DOCKERFILE_EXISTS == 'true'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: apps/${{ matrix.packages.name }}/Dockerfile
          tags: ${{ inputs.container-registry }}/${{ inputs.image-prefix }}/${{ matrix.packages.name }}:${{ matrix.packages.imageTag }}
          push: ${{ inputs.push }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update-gitops:
    needs: build-and-publish-docker-image

    if: inputs.update

    uses: ./.github/workflows/update-gitops.yaml
    with:
      packages: ${{ inputs.packages }}
      environment: ${{ inputs.environment }}
      image-prefix: ${{ inputs.image-prefix }}
      gitops-repository: ${{ inputs.gitops-repository }}
      gitops-ref: ${{ inputs.gitops-ref }}
      container-registry: ${{ inputs.container-registry }}
      mode: ${{ inputs.update-mode }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
