name: Deploy
on:
  push:
    branches:
      - feat/improve-deploy

permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  issues: write
  discussions: read
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: read
  statuses: write

jobs:
  deploy:
    name: Deploy
    strategy:
      matrix:
        node-version: [16.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
        name: Checkout [Pull Request]
        if: ${{ github.event_name == 'pull_request' }}
        with:
          # By default, PRs will be checked-out based on the Merge Commit, but we want the actual branch HEAD.
          ref: ${{ github.event.pull_request.head.sha }}
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0

      - uses: actions/checkout@v2
        name: Checkout [Default Branch]
        if: ${{ github.event_name != 'pull_request' }}
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      # - name: Set dev web env
      #   if: ${{ github.ref == 'refs/heads/dev' }}
      #   run: mv apps/cugetreg-web/.env.dev apps/cugetreg-web/.env

      # - name: Set beta web env
      #   if: ${{ github.ref == 'refs/heads/beta' }}
      #   run: mv apps/cugetreg-web/.env.beta apps/cugetreg-web/.env

      # - name: Set prod web env
      #   if: ${{ github.ref == 'refs/heads/master' }}
      #   run: mv apps/cugetreg-web/.env.prod apps/cugetreg-web/.env

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      # - name: Docker login
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ github.token }}

      - name: Affected apps
        run: |
          AFFECTED_BASE=${{ github.event.before }} ./tools/affected-apps

      - name: Build Docker images
        run: |
          npx nx run-many --target=docker-build --configuration=${{ github.ref_name }} --parallel --projects=${{ env.AFFECTED_APPS }}

      # - name: Connect SSLVPN
      #   uses: thinc-org/openfortivpn-action@master
      #   with:
      #     host: ${{ secrets.SSLVPN_HOST }}
      #     username: ${{ secrets.SSLVPN_USERNAME }}
      #     password: ${{ secrets.SSLVPN_PASSWORD }}
      #     trustedCert: ${{ secrets.SSLVPN_TRUSTED_CERT }}

      # - name: Deploy to VM
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     key: ${{ secrets.SSH_KEY }}
      #     passphrase: ${{ secrets.SSH_PASSPHRASE }}
      #     script: |
      #       docker pull ghcr.io/thinc-org/cugetreg/cugetreg-api:dev
      #       docker pull ghcr.io/thinc-org/cugetreg/cugetreg-api:beta
      #       docker pull ghcr.io/thinc-org/cugetreg/cugetreg-api:latest
      #       docker pull ghcr.io/thinc-org/cugetreg/cugetreg-web:dev
      #       docker pull ghcr.io/thinc-org/cugetreg/cugetreg-web:beta
      #       docker pull ghcr.io/thinc-org/cugetreg/cugetreg-web:latest
      #       docker-compose up -d
      #       if [[ "$(docker images --filter "dangling=true" -q)" == "" ]];
      #         then echo "No image with <none> tag";
      #         else docker rmi $(docker images --filter "dangling=true" -q);
      #       fi
