name: E2E test

on:
  pull_request:
  push:
    # branches: [master]
    branches: [master, beta]

permissions:
  contents: write
  packages: read
  pull-requests: write
  repository-projects: read
  checks: write
  actions: read

jobs:
  e2e:
    needs: [install-depedencies]
    strategy:
      matrix:
        node-version: [14.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    env:
      LHCI_SERVER_TOKEN: ${{ secrets.LHCI_SERVER_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --fronzen-lockfile

      - name: Build project
        run: yarn build

      - run: yarn test --projects jest-puppeteer.config.js
