name: Release - Dev

on:
  push:
    branches:
      - dev

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  issues: write
  discussions: read
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: read
  statuses: write

jobs:
  release:
    name: Release dev

    strategy:
      matrix:
        node-version: [16.17.0]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    if: ${{ github.event_name != 'workflow_dispatch' }}

    outputs:
      affectedPackages: ${{ steps.affected-packages.outputs.affectPackages }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Install turbo
        run: pnpm install --global turbo

      - name: Get affected app names
        id: affected-apps
        run: |
          PACKAGES=$(pnpm turbo run build --filter='...[origin/beta]' --dry=json | jq -c '.packages | map(select(. != "//"))')
          echo "packages=$PACKAGES" >> $GITHUB_OUTPUT
          echo "packages=$PACKAGES"

      - name: Generate affected packages
        id: affected-packages
        run: |
          PACKAGES='${{ steps.affected-apps.outputs.packages }}'
          PACKAGES_OUTPUT=$(echo $PACKAGES | jq -c 'map_values({name:.,ref:"refs/heads/dev",imageTag:"dev"})')
          echo "affectPackages=$PACKAGES_OUTPUT" >> $GITHUB_OUTPUT
          echo "affectPackages=$PACKAGES_OUTPUT"

      - name: Print Debug
        run: echo "${{ steps.affected-packages.outputs.affectPackages }}"

  deploy-with-docker:
    needs:
      - release
    uses: ./.github/workflows/deploy-docker.yaml
    with:
      packages: ${{ needs.release.outputs.affectedPackages }}
      container-registry: ghcr.io
      image-prefix: thinc-org/cugetreg
      username: ${{ github.actor }}
      password: ${{ github.token }}
      # target-repository: ${{ github.repository }}
      # target-ref: main
      # target-directory: k8s-demo
      push: true
      update: false
      checkout-with-ref: false
