name: Deploy Storybook

on:
  push:
    branches:
      - v2
    paths:
      - 'apps/storybook/**'
      - 'packages/ui/**'

jobs:
  storybook:
    name: Storybook
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node with cache
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm turbo run --filter=@app/storybook build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          # Using @leomotors's API token
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: cugetreg-storybook
          directory: apps/storybook/storybook-static
