name: Test reusable

on:
  push:
    branches: [mvp1-dev]

jobs:
  test-deploy:
    uses: ./.github/workflows/build-deploy.yaml
    with:
      env: beta
      tag: test-${{ github.sha }}
      update-mode: pr
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
