name: Test no permissions

on:
  workflow_call:
    inputs:
      greeting:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}"
