name: Run test coverage

on:
  pull_request:
  push:
    branches: [beta, dev, master]

jobs:
  test:
    strategy:
      matrix:
        node-version: [14.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - name: Wait for install depedencies
        if: github.event_name == 'pull_request'
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-install
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: install-depedencies
          ref: ${{ github.head_ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: yarn --fronzen-lockfile

      - name: Collect test coverage
        run: yarn test:ci

      - name: Extract code coverage
        uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: yarn
          annotations: failed-tests
          skip-step: all
